version: "3"
services:
  # MongoDB
  db:
    image: mongo:latest
    container_name: db_container
    restart: unless-stopped
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    networks:
      - app-network

  # FastAPI
  api:
    # image: python:3.8-slim-buster
    image: python:3.8
    container_name: api_container
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/eXchangeAPI/
    working_dir: /usr/src/eXchangeAPI
    command: sh commands.sh
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver_container
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  db-data:
    driver: local
  mongo-config:
    driver: local
